// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteHistoryItem(arg1:string):Promise<void>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetHistory(arg1:number,arg2:string):Promise<Array<app.HistoryItem>>;

export function LoadHistoryItem(arg1:string):Promise<app.HistoryItem>;

export function SendRequest(arg1:app.HTTPRequest):Promise<app.HTTPResponse>;
