// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function DeleteHistoryItem(arg1) {
  return window['go']['app']['App']['DeleteHistoryItem'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetHistory(arg1, arg2) {
  return window['go']['app']['App']['GetHistory'](arg1, arg2);
}

export function LoadHistoryItem(arg1) {
  return window['go']['app']['App']['LoadHistoryItem'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['app']['App']['SendRequest'](arg1);
}
