// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppInfo():Promise<main.AppInfo>;

export function Greet(arg1:string):Promise<string>;

export function SendRequest(arg1:main.HTTPRequest):Promise<main.HTTPResponse>;
